M48
; DRILL file {KiCad 7.0.2} date Thu Jun  6 15:55:00 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-06T15:55:00-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
%
G90
G05
T1
X3.35Y-2.325
X3.4787Y-4.0614
X4.9713Y-2.3136
X5.0787Y-4.0364
X5.4463Y-2.7136
T0
M30
